DATA:
    ROOT: '/PATH/TO/videos/folder'
    TRAIN_FILE: 'datasets_splits/base2novel_splits/ssv2_splits/fs_base_s1_train.txt'
    VAL_FILE: 'datasets_splits/base2novel_splits/ssv2_splits/base_val.txt'
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 87
    LABEL_LIST: 'labels/ssv2_174_base_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 11
    LR: 2.e-06
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 10